#!/bin/bash

if [[ $# -lt 1 ]]
then
    echo "$0 BUILD_COMMAND"
    exit 1
fi

if [[ -f "Makefile" ]]
then
    cp "Makefile" "Makefile.`date +%s`"
fi

cat > "Makefile" << EOF
ALL:
	 bash -c "$@ 2>&1"
EOF
